export enum ErrorCode {
  // General errors
  SERVER_ERROR = 'SERVER_ERROR',
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  NOT_FOUND = 'NOT_FOUND',
  
  // User errors
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  USER_EXISTS = 'USER_EXISTS',
  USER_ID_REQUIRED = 'USER_ID_REQUIRED',
  USER_ID_INVALID = 'USER_ID_INVALID',
  
  // File upload errors
  FILE_UPLOAD_ERROR = 'FILE_UPLOAD_ERROR',
  FILE_TYPE_INVALID = 'FILE_TYPE_INVALID',
  
  // Auth validation errors
  AUTH_HEADER_REQUIRED = 'AUTH_HEADER_REQUIRED',
  PASSWORD_CHANGE_FAILED = 'PASSWORD_CHANGE_FAILED',
  INVALID_TOKEN = 'INVALID_TOKEN',
  TOKEN_EXPIRED = 'TOKEN_EXPIRED',
  
  // Input validation errors
  MISSING_REQUIRED_FIELDS = 'MISSING_REQUIRED_FIELDS',
  INVALID_EMAIL_FORMAT = 'INVALID_EMAIL_FORMAT',
  INVALID_PHONE_FORMAT = 'INVALID_PHONE_FORMAT',
} 